#!/bin/bash


read first
read second
echo "first = $first and second = $second"
echo $(( first + second ))
echo $(( first - second ))
echo $(( first * second ))
echo $(( first / second ))
echo $(( first % second ))
