#!/bin/bash

echo "Enter filename to print from awk"
read fileName

if [[ -f "$fileName" ]]
then
    # Напечатать четвёртое слово тех строк, где Linux
    awk '/Linux/ {print $2,$4}' $fileName
else
    echo "$fileName doesn't exist"
fi
