#!/bin/bash

echo "Enter filename to search text from"
read fileName

if [[ -f "$fileName" ]]
then
    echo "Enter the text to search"
    read grepvar
    # grep без параметров - ищет слова с учетом регистра
    # -i без учёта регистра
    # -n выводит ещё и номер строки
    # -c количество найденных слов
    # -v все результаты противоположные заданному параметру
    grep -i -n -c $grepvar $fileName
else
    echo "$fileName doesn't exist"
fi
