#!/bin/bash

echo "enter 1st string"
read st1

echo "enter 2st string"
read st2

if [ "$st1" \> "$st2" ]
then
    echo "$st1 is bigger than $st2"
elif [ "$st1" \< "$st2" ]
then
    echo "$st2 is bigger $st1"
else
    echo "both strings are equal"
fi
